apiVersion: v1
kind: Service
metadata:
  name: prometheus-service
  namespace: monitoring
spec:
  type: NodePort  # Cambiar a ClusterIP si solo deseas acceso interno
  ports:
    - port: 9090
      targetPort: 9090
      nodePort: 30090  # Cambia este puerto si está en uso
  selector:
    app: prometheus  # Asegúrate que esto coincida con las labels del Deployment de Prometheus
