global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'kubernetes-nodes'
    kubernetes_sd_configs:
      - role: node

  - job_name: 'kubernetes-pods'
    kubernetes_sd_configs:
      - role: pod

  - job_name: 'nginx'
    static_configs:
      - targets: ['192.168.3.3:32010']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['192.168.3.3:30081']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['192.168.3.3:9100']
      
  - job_name: 'prometheus'
    static_configs:
      - targets: ['192.168.3.3:30090'] 

  - job_name: 'grafana'
    static_configs:
      - targets: ['192.168.3.3:32000'] 

  - job_name: 'jellyfin'
    static_configs:
      - targets: ['jellyfin-exporter.default.svc.cluster.local:9594']
 
  - job_name: 'asterisk'
    static_configs:
      - targets: ['192.168.3.3:30002']
    
