apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: default  # Cambia a 'default' si deseas que esté en ese namespace
  labels:
    app: nginx
spec:
  selector:
    app: nginx
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 31913  # Cambia este número si ya está en uso por otro servicio
  type: NodePort
