apiVersion: v1
kind: Service
metadata:
  name: cadvisor-service
  namespace: monitoring
spec:
  type: NodePort  # Cambiado para exponerlo fuera del clúster
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30081  # Puedes cambiarlo si ya está en uso
  selector:
    name: cadvisor  # Corregido para coincidir con el DaemonSet
