apiVersion: v1
kind: Service
metadata:
  name: asterisk-service
spec:
  selector:
    app: asterisk
  ports:
    - name: sip
      protocol: UDP
      port: 5060
      targetPort: 5060
      nodePort: 30060  # Para Linphone (externo)
    - name: prometheus-metrics
      protocol: TCP
      port: 8089
      targetPort: 8089
      nodePort: 30002  # Para Prometheus (externo)
  type: NodePort
